name: Update-Timestamp

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  push:
    branches:
      - main  # 或者你希望运行该工作流的其他分支

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 指定Node.js版本

    - name: Run script
      run: node script.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'smalltpgh'
        git config --global user.email 'smalltpgh@outlook.com'
        git add timestamp.txt
        git commit -m "Update timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
